// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:e97593d5-24ca-401f-adc1-24859c1a81cc',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'lindseyportfolio-hosting-mobilehub-1417702165',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2krgnti23k3s.cloudfront.net',
    'aws_mobile_analytics_app_id': '9428b827be664911826868b4c5a4f040',
    'aws_project_id': '9b91075b-2202-4f8e-acc6-b169e2d0a33d',
    'aws_project_name': 'lindsey-portfolio',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'lindseyportfolio-mobilehub-1417702165',
}

export default awsmobile;
